[features]
seeds = false
skip-lint = false

[programs.localnet]
creatorcoin_ai = "CrEaToRcOiNai11111111111111111111111111111"

[programs.devnet]
creatorcoin_ai = "CrEaToRcOiNai11111111111111111111111111111"

[programs.testnet]
creatorcoin_ai = "CrEaToRcOiNai11111111111111111111111111111"

[programs.mainnet]
creatorcoin_ai = "CrEaToRcOiNai11111111111111111111111111111"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
